const ONE_MINUTE = 1000 * 60;

const FIFTEEN_MINUTES = ONE_MINUTE * 15;

const THIRTY_MINUTES = ONE_MINUTE * 30;

const TWO_HOURS = THIRTY_MINUTES * 4;

export {
    FIFTEEN_MINUTES,
    THIRTY_MINUTES,
    TWO_HOURS
};